/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dosse.binaural.player.utils;

import com.dosse.binaural.player.Main;
import java.awt.Point;
import java.awt.Toolkit;
import java.io.File;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;

/**
 * it's a file chooser, that's all
 *
 * @author dosse
 */
public class FileChooser extends javax.swing.JDialog {

    private File selectedFile;
    private FileFilter selectedFF;
    private boolean done = false;
    private static String openTitle, saveTitle, overwriteConfirm;
    private static String lastPath = null;

    static {
        ResourceBundle bundle = ResourceBundle.getBundle("com/dosse/binaural/player/utils/FileChooser");
        openTitle = bundle.getString("FileChooser.open");
        saveTitle = bundle.getString("FileChooser.save");
        overwriteConfirm = bundle.getString("FileChooser.overwriteConfirm");
    }

    public File getSelectedFile() {
        return selectedFile;
    }

    /**
     * Creates new form MessageBox
     */
    public FileChooser(java.awt.Frame parent, boolean modal, FileFilter[] ff, Point location, boolean open) {
        super(parent, modal);
        initComponents();
        for (FileFilter f : ff) {
            jFileChooser1.addChoosableFileFilter(f);
        }
        jFileChooser1.setFileFilter(ff[0]);
        jFileChooser1.setAcceptAllFileFilterUsed(false);
        jFileChooser1.setMultiSelectionEnabled(false);
        jFileChooser1.setDialogType(open ? JFileChooser.OPEN_DIALOG : JFileChooser.SAVE_DIALOG);
        setTitle(open ? openTitle : saveTitle);
        title.setText(getTitle());
        setLocation(location.x - getWidth() / 2, location.y - getHeight() / 2);
        if (!Main.DISABLE_TRANSLUCENCY) {
            setOpacity(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        titleBar = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        jFileChooser1 = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        mainPanel.setBackground(new java.awt.Color(245, 245, 245));

        titleBar.setBackground(Main.brightTitleBar_focused);
        titleBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                titleBarMousePressed(evt);
            }
        });
        titleBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                titleBarMouseDragged(evt);
            }
        });

        title.setFont(Main.bold.deriveFont(13.0f));
        title.setForeground(Main.darkText);
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/dosse/binaural/player/utils/FileChooser"); // NOI18N
        title.setText(bundle.getString("FileChooser.title.text")); // NOI18N

        javax.swing.GroupLayout titleBarLayout = new javax.swing.GroupLayout(titleBar);
        titleBar.setLayout(titleBarLayout);
        titleBarLayout.setHorizontalGroup(
            titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
        );
        titleBarLayout.setVerticalGroup(
            titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
        );

        jFileChooser1.setCurrentDirectory(new File(lastPath!=null?lastPath:""));
        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addComponent(titleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFileChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        getContentPane().add(mainPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private int dragStartX, dragStartY;
    private void titleBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleBarMousePressed
        dragStartX = evt.getX();
        dragStartY = evt.getY();
    }//GEN-LAST:event_titleBarMousePressed

    private void titleBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleBarMouseDragged
        setLocation(evt.getXOnScreen() - dragStartX, evt.getYOnScreen() - dragStartY);
    }//GEN-LAST:event_titleBarMouseDragged

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
        if (evt.getActionCommand().equals(JFileChooser.APPROVE_SELECTION)) {
            selectedFile = jFileChooser1.getSelectedFile();
            if (jFileChooser1.getDialogType() == JFileChooser.SAVE_DIALOG && selectedFile != null && selectedFile.exists()) {
                setAlwaysOnTop(false);
                int sel = YesNoCancelDialog.confirm(overwriteConfirm, title.getText(), true);
                setAlwaysOnTop(true);
                if (sel == YesNoCancelDialog.NO) {
                    selectedFile = null;
                    return;
                }
                if (sel == YesNoCancelDialog.CANCEL) {
                    selectedFile = null;
                }
            }
            if (selectedFile != null) {
                lastPath = selectedFile.getParent();
            }
            selectedFF = jFileChooser1.getFileFilter();
        }
        done = true;
        if (Main.DISABLE_TRANSLUCENCY) {
            dispose();
            return;
        }
        setOpacity(1);
        for (float i = 1; i >= 0; i -= 0.1) {
            setOpacity(i);
            try {
                Thread.sleep(20);
            } catch (InterruptedException ex) {
            }
        }
        setOpacity(0);
        dispose();
    }//GEN-LAST:event_jFileChooser1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if (Main.DISABLE_TRANSLUCENCY) {
            return;
        }
        new Thread() {
            public void run() {
                for (float i = 0; i <= 1; i += 0.1) {
                    setOpacity(i);
                    try {
                        Thread.sleep(20);
                    } catch (InterruptedException ex) {
                    }
                }
                setOpacity(1);
            }
        }.start();
    }//GEN-LAST:event_formWindowOpened

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        titleBar.setBackground(Main.brightTitleBar_focused);
    }//GEN-LAST:event_formWindowGainedFocus

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        titleBar.setBackground(Main.brightTitleBar_unfocused);
    }//GEN-LAST:event_formWindowLostFocus
    //return an Object[2]: first element is the actual file; second element is the file filter selected by the user (from the FileFilter[] array)

    public static Object[] show(FileFilter[] ff, boolean openDialog) {
        FileChooser dialog = new FileChooser(new javax.swing.JFrame(), true, ff, new Point(Toolkit.getDefaultToolkit().getScreenSize().width / 2, Toolkit.getDefaultToolkit().getScreenSize().height / 2), openDialog);
        dialog.setVisible(true);
        while (!dialog.done) {
            try {
                Thread.sleep(100);
            } catch (InterruptedException ex) {
                Logger.getLogger(FileChooser.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return new Object[]{dialog.selectedFile, dialog.selectedFF};
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel title;
    private javax.swing.JPanel titleBar;
    // End of variables declaration//GEN-END:variables
}
