/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dosse.binaural.player.utils;

import com.dosse.binaural.player.Main;
import java.awt.Point;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * simple message box, nothing interesting
 *
 * @author dosse
 */
public class YesNoCancelDialog extends javax.swing.JDialog {
    
    //constants
    public static final int YES = 0, NO = 1, CANCEL=2;

    /**
     * Creates new form MessageBox
     */
    public YesNoCancelDialog(java.awt.Frame parent, boolean modal, String message, String title, Point location, boolean cancelable) {
        super(parent, modal);
        initComponents();
        this.message.setText(message);
        this.title.setText(title);
        setTitle(title);
        setLocation(location.x - getWidth() / 2, location.y - getHeight() / 2);
        if(!cancelable) cancel.setVisible(false);
        if (!Main.DISABLE_TRANSLUCENCY) {
            setOpacity(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        buttonBar = new javax.swing.JPanel();
        yes = new javax.swing.JLabel();
        no = new javax.swing.JLabel();
        cancel = new javax.swing.JLabel();
        titleBar = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        message = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        mainPanel.setBackground(new java.awt.Color(245, 245, 245));

        buttonBar.setBackground(Main.brightButtonBar);

        yes.setBackground(Main.brightButton_normal);
        yes.setFont(Main.reg.deriveFont(14.0f));
        yes.setForeground(Main.darkText);
        yes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/dosse/binaural/player/utils/YesNoCancelDialog"); // NOI18N
        yes.setText(bundle.getString("YesNoCancelDialog.yes.text")); // NOI18N
        yes.setOpaque(true);
        yes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                yesMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yesMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                yesMousePressed(evt);
            }
        });

        no.setBackground(Main.brightButton_normal);
        no.setFont(Main.reg.deriveFont(14.0f));
        no.setForeground(Main.darkText);
        no.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        no.setText(bundle.getString("YesNoCancelDialog.no.text")); // NOI18N
        no.setOpaque(true);
        no.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                noMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                noMousePressed(evt);
            }
        });

        cancel.setBackground(Main.brightButton_normal);
        cancel.setFont(Main.reg.deriveFont(14.0f));
        cancel.setForeground(Main.darkText);
        cancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancel.setText(bundle.getString("YesNoCancelDialog.cancel.text")); // NOI18N
        cancel.setOpaque(true);
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cancelMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cancelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout buttonBarLayout = new javax.swing.GroupLayout(buttonBar);
        buttonBar.setLayout(buttonBarLayout);
        buttonBarLayout.setHorizontalGroup(
            buttonBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                .addComponent(yes, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(no, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        buttonBarLayout.setVerticalGroup(
            buttonBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yes, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(no, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        titleBar.setBackground(Main.brightTitleBar_focused);
        titleBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                titleBarMousePressed(evt);
            }
        });
        titleBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                titleBarMouseDragged(evt);
            }
        });

        title.setFont(Main.bold.deriveFont(13.0f));
        title.setForeground(Main.darkText);
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText(bundle.getString("YesNoCancelDialog.title.text")); // NOI18N

        javax.swing.GroupLayout titleBarLayout = new javax.swing.GroupLayout(titleBar);
        titleBar.setLayout(titleBarLayout);
        titleBarLayout.setHorizontalGroup(
            titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        titleBarLayout.setVerticalGroup(
            titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
        );

        message.setFont(Main.reg.deriveFont(14.0f));
        message.setForeground(Main.darkText);
        message.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/dosse/binaural/player/utils/question.png"))); // NOI18N
        message.setText(bundle.getString("YesNoCancelDialog.message.text")); // NOI18N

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(titleBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(message, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addComponent(titleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(message, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(mainPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void fadeOut(){
        if (Main.DISABLE_TRANSLUCENCY) {
            return;
        }
        setOpacity(1);
        for (float i = 1; i >= 0; i -= 0.1) {
            setOpacity(i);
            try {
                Thread.sleep(20);
            } catch (InterruptedException ex) {
            }
        }
        setOpacity(0);
        
    }
    private void yesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yesMouseClicked
        selection=YES;
        done=true;
        fadeOut();
        dispose();
    }//GEN-LAST:event_yesMouseClicked
    private int dragStartX, dragStartY;
    private void titleBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleBarMousePressed
        dragStartX = evt.getX();
        dragStartY = evt.getY();
    }//GEN-LAST:event_titleBarMousePressed

    private void titleBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleBarMouseDragged
        setLocation(evt.getXOnScreen() - dragStartX, evt.getYOnScreen() - dragStartY);
    }//GEN-LAST:event_titleBarMouseDragged

    private void yesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yesMousePressed
        yes.setBackground(Main.brightButton_pressed);
    }//GEN-LAST:event_yesMousePressed

    private void yesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yesMouseReleased
        yes.setBackground(Main.brightButton_normal);
    }//GEN-LAST:event_yesMouseReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if (Main.DISABLE_TRANSLUCENCY) {
            return;
        }
        new Thread() {
            public void run() {
                for (float i = 0; i <= 1; i += 0.1) {
                    setOpacity(i);
                    try {
                        Thread.sleep(20);
                    } catch (InterruptedException ex) {
                    }
                }
                setOpacity(1);
            }
        }.start();
    }//GEN-LAST:event_formWindowOpened

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        titleBar.setBackground(Main.brightTitleBar_focused);
    }//GEN-LAST:event_formWindowGainedFocus

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        titleBar.setBackground(Main.brightTitleBar_unfocused);
    }//GEN-LAST:event_formWindowLostFocus

    private void noMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noMouseReleased
        no.setBackground(Main.brightButton_normal);
    }//GEN-LAST:event_noMouseReleased

    private void noMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noMouseClicked
        selection=NO;
        done=true;
        fadeOut();
        dispose();
    }//GEN-LAST:event_noMouseClicked

    private void noMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noMousePressed
        no.setBackground(Main.brightButton_pressed);
    }//GEN-LAST:event_noMousePressed

    private void cancelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseReleased
        no.setBackground(Main.brightButton_normal);
    }//GEN-LAST:event_cancelMouseReleased

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        selection=CANCEL;
        done=true;
        fadeOut();
        dispose();
    }//GEN-LAST:event_cancelMouseClicked

    private void cancelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMousePressed
        cancel.setBackground(Main.brightButton_pressed);
    }//GEN-LAST:event_cancelMousePressed

    private boolean done=false;
    private int selection=-1;
    
    public static int confirm(String message, String title, boolean cancelable) {
        YesNoCancelDialog dialog = new YesNoCancelDialog(new javax.swing.JFrame(), true, "<html>" + message + "</html>", "<html>" + title + "</html>", new Point(Toolkit.getDefaultToolkit().getScreenSize().width / 2, Toolkit.getDefaultToolkit().getScreenSize().height / 2),cancelable);
        dialog.setVisible(true);
        while(!dialog.done){
            try {
                Thread.sleep(100);
            } catch (InterruptedException ex) {
                Logger.getLogger(YesNoCancelDialog.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return dialog.selection;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonBar;
    private javax.swing.JLabel cancel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel message;
    private javax.swing.JLabel no;
    private javax.swing.JLabel title;
    private javax.swing.JPanel titleBar;
    private javax.swing.JLabel yes;
    // End of variables declaration//GEN-END:variables
}
